- hosts: localhost
  connection: local
  gather_facts: False
  vars_files: 
    - vars_file.yml

  tasks:
    - name: Provision a set of instances
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: LinuxKeyPair
        region: us-west-2
        vpc_subnet_id: subnet-d8de6990
        group_id: sg-5efc7d23
        instance_type: t2.micro
        image: "{{ ami_id }}"
        wait: yes 
        exact_count: 1
        count_tag:
          Name: ec2-Demo
        instance_tags:
          Name: ec2-Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: 
        hostname: "{{ item.private_ip }}" 
        groups: ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: add hosts to hosts files
      shell: echo "{{ item.private_ip }}" >> hosts
      with_items: "{{ ec2.instances }}"

    - name: wait 300 seconds and continue
      wait_for: timeout=300
      delegate_to: localhost

    - name: Wait for system to become reachable
      wait_for:
        port: 22
        delay: 60

- hosts: ec2hosts
  name: configuration play
  user: ec2-user
  gather_facts: true

  tasks:
    - name: Check NTP service
      service: name=ntp state=started