- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  tasks:
    - name: Gather EC2 Facts
      ec2_remote_facts:
        region: us-west-2
      register: ec2_facts

    - name: Debug
      debug:
        msg: "{{ ec2_facts }}"

    #- name: Provision a set of instances
      #ec2:
        #state: absent