- hosts: localhost
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: Getting instance facts
      ec2_instance_facts:
        region: us-west-2
        filters:
          "private-ip-address": "10.0.200.120"
      register: ec2_info

    - name: debug
      debug: msg="{{ ec2_info.instances }}"

    - name: Add all instance public IPs to host group
      add_host: 
        hostname: "{{ item }}" 
        groups: ec2instanceid
      with_items: "{{ ec2_info.instances.[].instance_id }}"

#---------------------------------------------
#- hosts: localhost
#  connection: local
#  gather_facts: True
#  become: False

#  tasks:
#    - ec2_instance_facts:
#        region: "us-west-2"
#        filters:
#          "private-ip-address": "10.0.200.120"
#      register: ec2_info

#    - debug: msg="{{ ec2_info.instances[].id }}"