- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  tasks:
    - name: Gather EC2 Facts
      ec2_remote_facts:
        region: us-west-2
      register: ec2-facts

    - name: Debug
      debug:
        msg: "Instance: {{ item.0 }} has IP address: {{ item.1 }}"
      with_together:
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"

    #- name: Provision a set of instances
      #ec2:
        #state: absent