- hosts: all
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: debug1
      debug: msg="{{ inventory_hostname }}"

    - name: Getting instance facts
      ec2_instance_facts:
        region: us-west-2
      register: ec2_info

    - name: debug
      debug: msg="{{ ec2_info }}"

    - name: initialize an empty list
      set_fact:
        instanceids_strings: []

    - name: Display Instance IDs based on ip
      set_fact:
        instanceids_strings: "{{ instanceids_strings + [ item ] }}"
      loop: "{{ ec2_info| json_query(server_ip_query) }}"
      vars:
        server_ip_query: "instances[?private_ip_address=='{{ inventory_hostname }}'].instance_id"

    - name: Term instances
      ec2:
        region: us-west-2
        state: stopped
        instance_ids: "{{ item }}"
      with_items: "{{ instanceids_strings }}"

      