- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  tasks:
    - name: Gather EC2 Facts
      ec2_remote_facts:
        region: us-west-2
      register: ec2_facts

    - name: Debug
      debug:
        msg: "{{ ec2_facts }}"
    
    - name: Get Instance ids
      set_fact:
        instance_ids: "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"
    
    - name: Jinja list debug, printing out the list as comma seperated.
      debug:
        msg: "{% for each in instance_ids %}{{ each }}{% if not loop.last %},{% endif %}{% endfor %}"

    #- name: Provision a set of instances
      #ec2:
        #state: absent