- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  tasks:
    - ec2_instance_facts:
        filters:
          "private_ip_address": "10.0.200.120"
      register: ec2_info

    - name: Debug
        debug: var=ec2_info
    
    #- name: Provision a set of instances
      #ec2:
        #state: absent