- hosts: localhost
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: Getting instance facts
      ec2_instance_facts:
        region: us-west-2
        filters:
          "private-ip-address": "10.0.200.120"
      register: ec2_info

    - name: debug
      debug: msg="{{ ec2_info.instances }}"
  
    - name: Add all instance public IPs to host group
      add_host: 
        hostname: "{{ item.instance_id }}" 
        groups: ec2instances
      with_items: "{{ ec2_info.instances }}"

    - name: Term instances
      ec2:
        region: us-west-2
        state: stopped
        instance_ids: "{{ item }}"
      with_items: "{{ ec2instances }}"



- hosts: ec2instances
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: term instances
      ec2:
        region: us-west-2
        state: stopped








    #- name: Add all instance public IPs to host group
    #  add_host: 
    #    hostname: "{{ item.instance_id }}" 
    #    groups: ec2instances
    #  with_items: "{{ ec2_info.instances }}"

    #- name: test
    #  debug: msg="{{ ec2instances.instance_id }}"

#---------------------------------------------
#- hosts: localhost
#  connection: local
#  gather_facts: True
#  become: False

#  tasks:
#    - ec2_instance_facts:
#        region: "us-west-2"
#        filters:
#          "private-ip-address": "10.0.200.120"
#      register: ec2_info

#    - debug: msg="{{ ec2_info.instances[].id }}"