- hosts: localhost
  connection: local
  gather_facts: True
  become: False

  tasks:
    - name: Gather EC2 Facts
        ec2_instance_facts:
          region: us-west-2
          filters:
            "private_ip_address": "10.0.200.120"
        register: ec2_info

    - name: Debug
        debug:
          msg: "{{ ec2_info }}"
    
    #- name: Provision a set of instances
      #ec2:
        #state: absent