- hosts: all
  connection: local
  gather_facts: False
  become: False

  tasks:
    - name: debug1
      debug: msg="{{ inventory_hostname }}"

    - name: Getting instance facts
      ec2_instance_facts:
        region: us-west-2
        filters:
          "private-ip-address": "{{ item }}"
      with_items: "{{ inventory_hostname }}"
      register: ec2_info

    - name: Iterate JSON - DEBUG
      debug: var=item.instances
      with_items: "{{ ec2_info.results }}"

    - name: Iterate JSON
      set_fact:
        instance: "{{ item.instances }}"
      with_items: "{{ ec2_info.results }}"
      register: instances

    - name: show instances
      debug: var=instances
      

    #- name: debug
      #debug: msg="{{ ec2_info.results }}"

    #- name: Add all instance private IPs to host group
      #add_host: 
        #results: "{{ item.instances }}" 
        #groups: ec2results
      #with_items: "{{ ec2_info.results }}"
    
    #- name: debug2
      #debug: msg="{{ groups['ec2results'] }}"
  
    #- name: Add all instance public IPs to host group
      #add_host: 
        #hostname: "{{ item.instance_id }}" 
        #groups: ec2instances
      #with_items: "{{ ec2_info.instances }}"

    #- name: Term instances
      #ec2:
        #region: us-west-2
        #state: stopped
        #instance_ids: "{{ item }}"
      #with_items: "{{ groups['ec2instances'] }}"

      